# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-state-a4ldev"
    encrypt = true
    key     = "sg-ripper/./terraform.tfstate"
    profile = "A4L-DEV"
    region  = "us-east-1"
  }
}
